### ISSUE TITLE
Faiss load_from_disk doesn't actually work

### ISSUE THREAD

**Issue by ricky-sb** [jerryjliu/gpt_index#162]
Here's a minimal example:

1. First, create and save the FAISS Index
```python
from gpt_index import GPTFaissIndex, SimpleDirectoryReader

faiss_index = faiss.IndexFlatL2(1536)
documents = SimpleDirectoryReader("data").load_data()
index = GPTFaissIndex(documents, faiss_index=faiss_index)
index.save_to_disk("index_faiss.json", faiss_index_save_path="index_faiss_core.index")
```

2. Now, try and load the same index
```python
new_index = GPTFaissIndex.load_from_disk(
    save_path="index_faiss.json", faiss_index_save_path="index_faiss_core.index"
)
print(new_index._faiss_index.ntotal)
```

Notice that 0 documents exist.

And just to verify that loading it regularly works, try this:

```python
import faiss

faiss_index = faiss.read_index("index_faiss_core.index")
print(faiss_index.ntotal)
```

This was a weird one to track down, because it doesn't actually "fail". Instead, we always return Node 0 with a distance of infinity. 

I poked around the code a bit but couldn't figure out where exactly the bug is. Separately, we should also include a quick sanity check, just ensure that the `faiss_index` isn't empty if we're loading it from disk.

**Comment by jerryjliu** [comment]
Ooooh thanks for surfacing! 

The reason I called `reset` was because there was a risk that if there were embeddings originally in the faiss_index before passing to GPT Index, those embeddings could potentially be retrieved during top-k neighbor search during query-time, but  those embeddings don't have corresponding text associated with them (since they weren't created within gpt index), so it breaks our query. 

Of course this also led to the bug you discovered where loading the faiss index breaks.

I think what would make sense is for a param e.g. `reset_faiss_index` to be True by default, but when `load_from_disk` is called, that param is explicitly set to False.

**Comment by jerryjliu** [comment]
thanks! 🙏  let me know if anything else comes up
