### ISSUE TITLE
Best llm to use gpt_index

### ISSUE THREAD

**Issue by Keith-Hon** [jerryjliu/gpt_index#441]
OpenAI's models definitely have high quality. But suppose someone wants to achieve comparable results using self host models and gpt-index, what are the alternatives?

**Comment by AldawsariNLP** [comment]
+1 
 Good question (i was going to ask the same question). Using some other alternatives like FLAN-T5 with gpt-index would be great.

**Comment by AldawsariNLP** [comment]
see this issue  https://github.com/jerryjliu/gpt_index/issues/423#issue-1579871856

**Comment by Keith-Hon** [comment]
> see this issue [#423 (comment)](https://github.com/jerryjliu/gpt_index/issues/423#issue-1579871856)

Yeah I have looked at it. While we could use custom models with some modifications on our own, it seems to me that most open source models didn't get trained with external data sources in mind.

**Comment by logan-markewich** [comment]
Another concern is input length. Most open-source models have a very small max length (OPT is 2048, FLAN is 512!!). 

I think in the next few months though, we will see more open-source models with capabilities similar to OpenAI models. The research area is pretty hot right now.

**Comment by jerryjliu** [comment]
Since this is more of an issue of choosing the LLM and not an issue of how to use it with GPT Index (i think), i'm going to close the issue for now.

 Btw even if langchain doesn't support the llm you're looking to integrate, you can always subclass LLMPredictor to integrate your LLM. ping me if you get to that and i can help
