### ISSUE TITLE
testing/science underlying continuation prompts

### ISSUE THREAD

**Issue by fredzannarbor** [jerryjliu/gpt_index#506]
The default continuation prompt is:

`Given the new context, refine the original answer to better answer the question. If the context isn't useful, return the original answer.`

Out of curiosity (and always wanting to understand the fundamentals of things), what is the basis for this phrasing?  Was it arrived at entirely by trial and error?  Is there any variation if you substitute words like "interesting" for "useful", or add "very" useful (which would emphasize stuff first read)?  In a perfect world, there would be a deterministic, or at least a known, link between the internal operation of the LLMs and this external prompt behavior.  I have a feeling there isn't, but it would be interesting to know more.--Fred

**Comment by jerryjliu** [comment]
Yeah we didn't do too much tuning when we first created it. Luckily you can customize prompts here! https://gpt-index.readthedocs.io/en/latest/how_to/custom_prompts.html

Going to close this for now since it's less of an issue and more a discussion. feel free to followup in the discord! https://discord.gg/dGcwcsnxhU
