### ISSUE TITLE
Hello, I want to use the extra_info field to pass additional information, but I don't want to generate extra_info_str, because this parameter will affect the embedding generation

### ISSUE THREAD

**Issue by zouhuigang** [jerryjliu/gpt_index#665]
Hello, I want to use the extra_info field to pass additional information, but I don't want to generate extra_info_str, because this parameter will affect the embedding generation

<img width="649" alt="image" src="https://user-images.githubusercontent.com/15059874/223680621-c581f5f8-5f10-471f-99da-d6fca041b6ab.png">

**Comment by jerryjliu** [comment]
hi, you can set include_extra_info=False when building the index.

`index = GPTListIndex(..., include_extra_info=False)`

**Comment by zouhuigang** [comment]
You understand wrong, I want to use include_extra_info=True, but I don’t want extra_info_str, this parameter will be brought when getting get_text, which affects the generation of vector

**Comment by zouhuigang** [comment]
```
def get_text(self) -> str:
        """Get text."""
        text = super().get_text()
        result_text = (
            text if self.extra_info_str is None else f"{self.extra_info_str}\n\n{text}"
        )
        return result_text
```

**Comment by zouhuigang** [comment]
@jerryjliu

**Comment by stamler** [comment]
> hi, you can set include_extra_info=False when building the index.
> 
> `index = GPTListIndex(..., include_extra_info=False)`

@jerryjliu I'm just wanting to follow up on this since it's not well documented and it may clarify what I believe @zouhuigang  is askinf for. I'll clarify by stating my use case.

I have several thousand multi-page PDF documents I want to index. I want the query to be able to return the file name and the page number when it responds.

By my estimation, the best way to do this is to create a `Document` object for each page of each PDF and setting the `extra_info_str` to `page:N, filename:XYZ.pdf, path:/path/to/doc/XYZ.pdf, otherdata:MMMMM` when calling the `Document()` constructor.

However during index construction I don't want to create an embedding that includes this information! Instead, I just want to add the extra_info_str directly to the index for its corresponding node then have it included within the context passed to the LLM at query time.

Is this a supported feature? If not what would be the best way to go about achieving this?

**Comment by jerryjliu** [comment]
> You understand wrong, I want to use include_extra_info=True, but I don’t want extra_info_str, this parameter will be brought when getting get_text, which affects the generation of vector

what include_extra_info=False does is not include extra_info in get_text - does that make sense?
