### ISSUE TITLE
InvalidRequestError maximum context length when querying an Arabic pdf

### ISSUE THREAD

**Issue by amida47** [jerryjliu/gpt_index#702]
I tried using your tool with to QA an Arabic pdf (about 84 pages).
here it is the code I used:
```
# in case you wanted to download the same pdf
!!wget https://www.bkam.ma/ar/content/download/757666/8545665/loi%20bancaire%20ar%2022%20V2%20web.pdf

from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader

documents = SimpleDirectoryReader(input_files=["/content/loi bancaire ar 22 V2 web.pdf"]).load_data()
index = GPTSimpleVectorIndex(documents)
response = index.query("ما هو الحد الاقصى للتعويض الذي تضمنه الشركة المغربية لتدبير صناديق ضمان الودائع البنكية")
print(response)
```
but I get an InvalidRequestError
```
InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 4167 tokens (3911 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.
```

**Comment by Disiok** [comment]
Hey @amida47, this looks like a bug in our token estimation for international languages.

I think a quick hack to get around this issue is to manually set a lower `max_input_size` in the `PromptHelper` to account for the bug.

We have plans to improve our international languages support, but in the meanwhile, please join the discord community (https://discord.com/invite/dGcwcsnxhU) to get quicker response and support!

Closing the issue for now.

**Comment by chrischjh** [comment]
In that case, is there a way to skip the token estimation? This is really a showstopper to me .. 😂
