### ISSUE TITLE
How many tokens per search ?

### ISSUE THREAD

**Issue by aparekh5** [jerryjliu/gpt_index#94]
I am planning on integrating gpt_index into a project of mine. I would like to have semantic search over a document. Is this library as expensive as the pricing mentioned here -> https://gpttools.com/searchtokens ? 
Or is it that the initial build costs a lot of tokens and after the initial build it is much cheaper ? . Thanks

**Comment by aparekh5** [comment]
I saw the issue for Cost Tracking, i am just trying to get a general sense of how much it costs

**Comment by jerryjliu** [comment]
Good question! Adding better cost tracking is definitely a ticket item (see #56). In addition I'll be adding more explicit documentation about the cost of building each index; I will be doing this very soon. In the meantime here is the rough cost during build and query time: 

The following indices don't require GPT at all during building:
- GPTListIndex
- GPTSimpleKeywordTableIndex - uses a regex keyword extractor to extract keywords from each document
- GPTRAKEKeywordTableIndex - uses a RAKE keyword extractor to extract keywords from each document

The following indices do require GPT during build time: 
- GPTTreeIndex - use GPT to hierarchically summarize the text to build the tree
- GPTKeywordTableIndex - use GPT to extract keywords from each document

During query time, you also have a few different options to reduce GPT cost:
- If using GPTTreeIndex, setting child_branch_factor=2 will be more expensive than the default child_branch_factor=1 (polynomial vs logarithmic), because we traverse 2 children instead of just 1 for each parent node. 
- if using GPTListIndex, can do index.query(..., keyword="<keyword>") to filter out nodes that don't contain the keyword
- If using any GPTKeywordTableIndex subclass, you can do index.query(..., mode="simple") or index.query(..., mode="rake") to also use regex/RAKE keyword extractors on your query text.`

GPT will always be called to synthesize the final answer, but with some of the tips above you can reduce GPT usage during build and query time.

**Comment by jerryjliu** [comment]
Should be closed with #85
